const exams = [
  "SBI PO",
  "IBPS PO",
  "RRB PO",
  "SBI Clerk",
  "IBPS Clerk",
];

const reasoningTopics = [
  "Puzzle",
  "Seating Arrangement",
  "Syllogism",
  "Inequality",
  "Coding-Decoding",
  "Blood Relation",
  "Direction Sense",
  "Order Ranking",
  "Input Output",
  "Data Sufficiency",
  "Logical Reasoning",
  "Alphanumeric Series",
  "Machine Input",
  "Statement Assumption",
  "Statement Conclusion",
  "Cause and Effect",
];
const quantTopics = [
  "Simplification",
  "Approximation",
  "Number Series",
  "Quadratic Equation",
  "Data Interpretation",
  "Caselet DI",
  "Profit and Loss",
  "Simple Interest",
  "Compound Interest",
  "Time and Work",
  "Time Speed Distance",
  "Ratio and Proportion",
  "Percentage",
  "Average",
  "Partnership",
  "Mixture and Allegation",
  "Mensuration",
  "Probability",
  "Permutation and Combination",
  "Number System",
];
const englishTopics = [
  "Reading Comprehension",
  "Cloze Test",
  "Error Detection",
  "Sentence Improvement",
  "Para Jumbles",
  "Fillers",
  "Word Swap",
  "Phrase Replacement",
  "Vocabulary",
  "Idioms and Phrases",
  "Synonyms",
  "Antonyms",
  "Grammar",
  "Sentence Rearrangement",
];