export const syllabus: Record<string, string[]> = {
  "Quantitative Aptitude": [
    "Vedic Maths & Speed Calculation",
    "Number Series (Missing & Wrong)",
    "Simplification & Approximation",
    "Quadratic Equations",
    "Percentage",
    "Profit, Loss & Discount",
    "Simple & Compound Interest",
    "Ratio, Proportion & Partnership",
    "Average & Age Problems",
    "Mixture & Alligation",
    "Time, Work & Wages",
    "Pipes & Cisterns",
    "Speed, Time & Distance",
    "Boats & Streams",
    "Permutation, Combination & Probability",
    "Data Interpretation (Bar, Line & Pie)",
    "Data Interpretation (Radar, Caselet & Missing)",
    "Data Sufficiency"
  ],
  "Reasoning Ability": [
    "Alpha-Numeric Symbol Series",
    "Direction & Distance Sense",
    "Blood Relations",
    "Syllogism (Only/A Few patterns)",
    "Coding-Decoding",
    "Inequalities (Direct & Coded)",
    "Order & Ranking",
    "Circular Seating Arrangement",
    "Linear & Square Seating Arrangement",
    "Floor & Box Puzzles",
    "Scheduling Puzzles (Month/Day/Date)",
    "Machine Input-Output",
    "Critical Reasoning (Statement & Assumption)",
    "Critical Reasoning (Cause & Effect / Action)",
    "Data Sufficiency"
  ],
  "English Language": [
    "Reading Comprehension",
    "Cloze Test",
    "Error Spotting & Detection",
    "Sentence Improvement & Correction",
    "Para Jumbles & Sentence Rearrangement",
    "Fillers (Single, Double & Multiple)",
    "Word Swap & Column Matching",
    "Idioms, Phrases & Verbal Ability",
    "Vocabulary & Synonyms"
  ],
  "General Awareness": [
    "RBI History, Functions & Monetary Policy",
    "Banking Terms, Instrument Types & History",
    "Types of Accounts & Financial Inclusion",
    "Basel Norms & NPA Management",
    "Digital Banking, NPCI & Payment Systems",
    "National & International Current Affairs",
    "Summits, Conferences & Government Schemes",
    "Sports, Awards & Book Publications",
    "Static GK (National Parks & Wildlife Sanctuaries)",
    "Static GK (Currencies, Capitals & Thermal Plants)"
  ],
  "Computer Awareness": [
    "Computer Hardware Components & Peripherals",
    "History, Generations & Architectures",
    "Operating Systems & File Extensions",
    "MS Office (Word & PowerPoint)",
    "MS Excel (Formulas & Data Structures)",
    "Internet, Protocols & Email Operations",
    "Networking Models & Topology Layouts",
    "Cyber Security, Malware, Viruses & Firewalls",
    "Database Management Systems (DBMS)",
    "Computer Shortcuts & Abbreviations"
  ]
};